# ./docker-compose.yml

version: '3.8'

services:

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/data

  web:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - WEB_SERVER=${WEB_SERVER}
      - WEB_HOST=${WEB_HOST}
      - WEB_PORT=${WEB_PORT}

volumes:
  redis_data:
